### ISSUE TITLE
/summon a bit broken

### ISSUE THREAD

**Issue by DylanQ** [ossimc82/fabiano-swagger-of-doom#13]
for me when i do /summon <playername> the player for a brief moment (unless spammed with a hotkey) will be on top of me but will go back to their spot after. To the person that is being summoned they do not change locations on their end.

**Comment by ebf34e12952930cf** [comment]
I think it moves the player to your world, not your location.

**Comment by ossimc82** [comment]
I'll improve it  to summon the player at your position if he is in your world.

**Comment by DylanQ** [comment]
No, it doesn't. But even if it was supposed to... It doesn't do that either.

**Comment by DylanQ** [comment]
i.Value.Move(player.X, player.Y);
                    player.SendInfo("Player summoned!");
                    return true;

ossmic isn't it already supposed to?

**Comment by cp-nilly** [comment]
DylanQ, try looking at how teleporting works. It is functionally the same. I went ahead and stripped the related code for convenience.

``` c#
Move(obj.X, obj.Y);
UpdateCount++;

var pos = new Position()
{
     X = obj.X,
     Y = obj.Y
};
BroadcastSync(new Packet[]
{
     new GotoPacket()
     {
          ObjectId = Id,
          Position = pos
     },
     new ShowEffectPacket()
     {
          EffectType = EffectType.Teleport,
          TargetId = Id,
          PosA = pos,
          Color = new ARGB(0xFFFFFFFF)
     }
});
```

I didn't test the command personally but felt I would explain what I thought is wrong. Simply moving a player via the move command will not have the desired effect because the client is programmed to ignore the position of its player given from the server. That is why there is the goto packet. If you need to move a player, that packet must be used. Other than that, since an object's information changed, it is a good idea to increase its updatecount to ensure clients get the changed information as quickly as possible.
